# pinecone.yaml
provider:
  provider_tag: PINECONE
  embeddings_type: BEDROCK
pinecone:
  index_name: product-index
bedrock:
  region_name: us-east-1
  embeddings_model_id: amazon.titan-embed-text-v1
